#
# platform.mak - build target definition
#

#CFLAGS_PLATFORM=-DIBMPC
#NASMFLAGS_PLATFORM=-DIBMPC
CFLAGS_PLATFORM=-DNEC98 -DJAPAN -DFL_COUNT_BY_BYTE
NASMFLAGS_PLATFORM=-DNEC98 -DJAPAN -DFL_COUNT_BY_BYTE

ALLCFLAGS=$(ALLCFLAGS) $(CFLAGS_PLATFORM)
NASMFLAGS=$(NASMFLAGS) $(NASMFLAGS_PLATFORM)
